@startuml

interface Component {
    + void operation()
}

class Leaf implements Component {
    + void operation()
}

class Composite {
    - Component
    + void addComponent(Component)
    + void removeComponent(Component)
    + void operation()
}

Composite o--> Component

@enduml